# Generated by Django 2.2 on 2020-03-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='CEO',
            new_name='Senior',
        ),
        migrations.RenameField(
            model_name='projectmanager',
            old_name='HR',
            new_name='Senior',
        ),
        migrations.RenameField(
            model_name='teamlead',
            old_name='ProjectManager',
            new_name='Senior',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='TeamLead',
            new_name='Senior',
        ),
    ]
