# Generated by Django 2.2 on 2020-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeList', '0002_auto_20200303_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUpdate',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=40)),
                ('MobileNo', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
