# Generated by Django 2.2 on 2020-03-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('applied', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('paidleaves', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_and_time', models.CharField(max_length=20)),
                ('days', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
