# Generated by Django 2.2 on 2020-03-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20200303_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('applied_time', models.CharField(max_length=50)),
                ('approved_time', models.CharField(max_length=50)),
                ('days', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='pending',
            name='date_and_time',
            field=models.CharField(max_length=50),
        ),
    ]
