# Generated by Django 2.2 on 2020-01-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sregno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('smarks', models.IntegerField()),
                ('Aadhar', models.FileField(upload_to='')),
            ],
        ),
    ]
