# Generated by Django 2.2 on 2020-01-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_place_restaurant_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='restaurants', serialize=False, to='application.Place'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='application.Restaurant'),
        ),
    ]
