# Generated by Django 2.2 on 2020-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200303_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='hr', max_length=20),
            preserve_default=False,
        ),
    ]
